### ISSUE TITLE
Unusual Log Entries on 2008 R2

### ISSUE THREAD

**Issue by idoru78** [chocolatey/puppet-chocolatey#130]
Hi, after yesterdays issues I took advice and update to the latest PS module and the latest chocolatey 9.10 beta. Whilst everything works OK I get so very odd logs while chocolatey is installed. 

```
my_machine: Notice: /Stage[setup]/Chocolatey::Install/Windows_env[chocolatey_ChocolateyInstall_env]/ensure: created
    my_machine: Info: /Stage[setup]/Chocolatey::Install/Windows_env[chocolatey_ChocolateyInstall_env]: Scheduling refresh of Exec[install_chocolatey_official]
    my_machine: Debug: /Stage[setup]/Chocolatey::Install/Windows_env[chocolatey_ChocolateyInstall_env]: The container Class[Chocolatey::Install] will propagate my refresh event
    my_machine: Debug: 2016-06-08 10:51:09 +0100 C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy Bypass -Command - is running as pid: 1752
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Waited 50 milliseconds...
    my_machine: Debug: Wait object signaled
    my_machine: Debug: Waited 6500 total milliseconds.
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> ï»¿<ReturnResult><Property Name="exitcode">0</Property><Property Name="errormessag
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> e"></Property><Property Name="stdout">DQpNb2RlICAgICAgICAgICAgICAgIExhc3RXcml0Z
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> VRpbWUgICAgIExlbmd0aCBOYW1lICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KLS0tLSAgICAgICAgICAgICAgICAtLS0tLS0
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> tLS0tLS0tICAgICAtLS0tLS0gLS0tLSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCmQtLS0tICAgICAgICAwOC8wNi8yMDE2I
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> CAgICAxMDo1MSAgICAgICAgICAgIGNob2NJbnN0YWxsICAgICAgICAgICAgICAgICAgICAgICAgICAg
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgDQpVbmFibGUgdG8gYXBwbHkgcmVkaXJ
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> lY3Rpb24gZml4LiBFcnJvcjogWW91IGNhbm5vdCBjYWxsIGEgbWV0aG9kIG9uIGEgbnVsbC12YWx1ZW
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> QgZXhwcmVzc2lvbi4NCkRvd25sb2FkaW5nIGh0dHA6Ly93cDAwMTgzOC9OdUdldC9hcGkvdjIvcGFja
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> 2FnZS9jaG9jb2xhdGV5LzAuOS4xMC1iZXRhLTIwMTYwNTMxIHRvIEM6XFVzZXJzXHB1cHBldFxBcHBE
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> YXRhXExvY2FsXFRlbXBcDQpjaG9jb2xhdGV5XGNob2NJbnN0YWxsXGNob2NvbGF0ZXkuemlwDQpJbnN
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> 0YWxsaW5nIGNob2NvbGF0ZXkgb24gdGhpcyBtYWNoaW5lDQpXQVJOSU5HOiBJdCdzIHZlcnkgbGlrZW
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> x5IHlvdSB3aWxsIG5lZWQgdG8gY2xvc2UgYW5kIHJlb3BlbiB5b3VyIHNoZWxsIAogIGJlZm9yZSB5b
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> 3UgY2FuIHVzZSBjaG9jby4KV0FSTklORzogWW91IGNhbiBzYWZlbHkgaWdub3JlIGVycm9ycyByZWxh
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> dGVkIHRvIG1pc3NpbmcgbG9nIGZpbGVzIHdoZW4gCiAgdXBncmFkaW5nIGZyb20gYSB2ZXJzaW9uIG9
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> mIENob2NvbGF0ZXkgbGVzcyB0aGFuIDAuOS45LiAKICAnQmF0Y2ggZmlsZSBjb3VsZCBub3QgYmUgZm
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> 91bmQnIGlzIGFsc28gc2FmZSB0byBpZ25vcmUuIAogICdUaGUgc3lzdGVtIGNhbm5vdCBmaW5kIHRoZ
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> SBmaWxlIHNwZWNpZmllZCcgLSBhbHNvIHNhZmUuCldBUk5JTkc6IFVuYWJsZSB0byBhZGQgQ2hvY29s
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> YXRleSB0byB0aGUgcHJvZmlsZS4gWW91IHdpbGwgbmVlZCB0byBkbyBpdCBtYW51YWxseS4gRXJyb3I
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> gd2FzICdDYW5ub3QgYmluZCBhcmd1bWVudCB0byBwYXJhbWV0ZXIgJ1BhdGgnIGJlY2F1c2UgaXQgaX
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> MgYW4gZW1wdHkgc3RyaW5nLicKQ3JlYXRpbmcgQ2hvY29sYXRleUluc3RhbGwgYXMgYW4gZW52aXJvb
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> m1lbnQgdmFyaWFibGUgKHRhcmdldGluZyAnTWFjaGluZScpIA0KICBTZXR0aW5nIENob2NvbGF0ZXlJ
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> bnN0YWxsIHRvICdDOlxQcm9ncmFtRGF0YVxjaG9jb2xhdGV5Jw0KQWRkaW5nIE1vZGlmeSBwZXJtaXN
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> zaW9uIGZvciBjdXJyZW50IHVzZXIgdG8gJ0M6XFByb2dyYW1EYXRhXGNob2NvbGF0ZXknDQpXZSBhcm
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> Ugc2V0dGluZyB1cCB0aGUgQ2hvY29sYXRleSBwYWNrYWdlIHJlcG9zaXRvcnkuDQpUaGUgcGFja2FnZ
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> XMgdGhlbXNlbHZlcyBnbyB0byAnQzpcUHJvZ3JhbURhdGFcY2hvY29sYXRleVxsaWInDQogIChpLmUu
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> IEM6XFByb2dyYW1EYXRhXGNob2NvbGF0ZXlcbGliXHlvdXJQYWNrYWdlTmFtZSkuDQpBIHNoaW0gZml
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> sZSBmb3IgdGhlIGNvbW1hbmQgbGluZSBnb2VzIHRvICdDOlxQcm9ncmFtRGF0YVxjaG9jb2xhdGV5XG
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> JpbicNCiAgYW5kIHBvaW50cyB0byBhbiBleGVjdXRhYmxlIGluICdDOlxQcm9ncmFtRGF0YVxjaG9jb
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> 2xhdGV5XGxpYlx5b3VyUGFja2FnZU5hbWUnLg0KDQpDcmVhdGluZyBDaG9jb2xhdGV5IGZvbGRlcnMg
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> aWYgdGhleSBkbyBub3QgYWxyZWFkeSBleGlzdC4NCg0KY2hvY29sYXRleS5udXBrZyBmaWxlIG5vdCB
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> pbnN0YWxsZWQgaW4gbGliLg0KIEF0dGVtcHRpbmcgdG8gbG9jYXRlIGl0IGZyb20gYm9vdHN0cmFwcG
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> VyLg0KVGhpcyBpcyBob3cgYWRkIHRoZSBDaG9jb2xhdGV5IFByb2ZpbGUgbWFudWFsbHkuDQpGaW5kI
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> HlvdXIgJHByb2ZpbGUuIFRoZW4gYWRkIHRoZSBmb2xsb3dpbmcgbGluZXMgdG8gaXQ6DQoNCiRDaG9j
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> b2xhdGV5UHJvZmlsZSA9ICIkZW52OkNob2NvbGF0ZXlJbnN0YWxsXGhlbHBlcnNcY2hvY29sYXRleVB
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> yb2ZpbGUucHNtMSINCmlmIChUZXN0LVBhdGgoJENob2NvbGF0ZXlQcm9maWxlKSkgew0KICBJbXBvcn
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> QtTW9kdWxlICIkQ2hvY29sYXRleVByb2ZpbGUiDQp9DQpDaG9jb2xhdGV5IChjaG9jby5leGUpIGlzI
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> G5vdyByZWFkeS4NCllvdSBjYW4gY2FsbCBjaG9jbyBmcm9tIGFueXdoZXJlLCBjb21tYW5kIGxpbmUg
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> b3IgcG93ZXJzaGVsbCBieSB0eXBpbmcgY2hvY28uDQpSdW4gY2hvY28gLz8gZm9yIGEgbGlzdCBvZiB
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> mdW5jdGlvbnMuDQpZb3UgbWF5IG5lZWQgdG8gc2h1dCBkb3duIGFuZCByZXN0YXJ0IHBvd2Vyc2hlbG
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> wgYW5kL29yIGNvbnNvbGVzDQogZmlyc3QgcHJpb3IgdG8gdXNpbmcgY2hvY28uDQpBbnkgZXJyb3JzI
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> HRoYXQgb2NjdXJlZCBkdXJpbmcgaW5zdGFsbCBvciB1cGdyYWRlIGFyZSBsb2dnZWQgaGVyZTogDQpF
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> bnN1cmluZyBjaG9jb2xhdGV5IGNvbW1hbmRzIGFyZSBvbiB0aGUgcGF0aA0KRW5zdXJpbmcgY2hvY29
    my_machine: 
    my_machine: Debug: 2016-06-08 10:51:53 +0100 PIPE> sYXRleS5udXBrZyBpcyBpbiB0aGUgbGliIGZvbGRlcg0KDQoNCg==</Property></ReturnResult>
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: WARNING: It's very likely you will need to close and reopen your shell 
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns:   before you can use choco.
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: WARNING: You can safely ignore errors related to missing log files when 
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns:   upgrading from a version of Chocolatey less than 0.9.9. 
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns:   'Batch file could not be found' is also safe to ignore. 
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns:   'The system cannot find the file specified' - also safe.
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: WARNING: Unable to add Chocolatey to the profile. You will need to do it manually. Error was 'Cannot bind argument to parameter 'Path' because it is an empty string.'
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: 
    my_machine: Notice: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: executed successfully
    my_machine: Debug: /Stage[setup]/Chocolatey::Install/Exec[install_chocolatey_official]: The container Class[Chocolatey::Install] will propagate my refresh event
```

All chocolatey packages seem to install OK after this.
